<?php

namespace AppBundle\Repository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends \Doctrine\ORM\EntityRepository
{
//    public function getEpisodeComingSoon($dateTime)
//    {
//        $episodes = $this->createQueryBuilder('e')
//            ->where('e.date >= :datetime')
//            ->setParameter('datetime', $dateTime)
//            ->orderBy('e.date', 'ASC');
//
//        return $episodes
//            ->getQuery()
//            ->getResult();
//    }
}
